/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Stanley Creative (https://sketchfab.com/Stanley_Creative)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/falcon-9-spacex-394f7cf52d124bbd9db69f24d1ff2f08
Title: Falcon 9 - SpaceX
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Falcon(props) {
  const { nodes, materials } = useGLTF("/models/falcon.glb");
  const modelRef = useRef();
  useFrame(() => {
    modelRef.current.rotation.y += 0.007;
  });
  return (
    <group
      {...props}
      dispose={null}
      ref={modelRef}
      scale={[0.0007075, 0.0007075, 0.0007075]}
      position={[0, -2, 0]}
    >
      <group rotation={[0, -Math.PI / 2, 0]} scale={100}>
        <group
          position={[0, 48.65, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1, 1, 0.237]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Second_Stage_F9_Second_Stage_0.geometry}
            material={materials.F9_Second_Stage}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Second_Stage_F9_Black_0.geometry}
            material={materials.F9_Black}
          />
          <group position={[0, 0, 18.708]} scale={[1, 1, 4.212]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Second_Stage_Raceways_F9_Second_Stage_0.geometry}
              material={materials.F9_Second_Stage}
              rotation={[0, 0, Math.PI]}
            />
          </group>
          <group
            position={[0, -1.354, -7.425]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[1, 1, 4.212]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes.Merlin_1D_Engine_Center001_Merlin_Engine_2_0.geometry
              }
              material={materials.Merlin_Engine_2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes.Merlin_1D_Engine_Center001_Merlin_Engine_3_0.geometry
              }
              material={materials.Merlin_Engine_3}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.Second_Stage_Detacher_Stage_F9_Second_Stage_0.geometry
            }
            material={materials.F9_Second_Stage}
            position={[0, 0, -5.789]}
            rotation={[0, 0, -2.094]}
            scale={[1, 1, 4.212]}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 1.025]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.First_Stage_F9_First_Stage_0.geometry}
            material={materials.F9_First_Stage}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.First_Stage_F9_Octaweb_Black_0.geometry}
            material={materials.F9_Octaweb_Black}
          />
          <group
            position={[0, 0, 40.643]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[1, 1, 0.168]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Interstage_F9_Black_0.geometry}
              material={materials.F9_Black}
            />
            <group
              position={[0, 0, -2.999]}
              rotation={[0, 0, -2.356]}
              scale={[2.044, 2.044, 11.903]}
            >
              <group rotation={[0, 0, -1.571]} scale={0.489}>
                <group rotation={[0, 0, -Math.PI / 2]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Grid_Fin_Controllers_F9_Black_0.geometry}
                    material={materials.F9_Black}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Grid_Fin_Controllers_F9_Grid_Fin_0.geometry}
                    material={materials.F9_Grid_Fin}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.Grid_Fin_Controllers_Metal_White_Gold_0.geometry
                    }
                    material={materials.Metal_White_Gold}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Grid_Fins_F9_Grid_Fin_0.geometry}
                    material={materials.F9_Grid_Fin}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Grid_Fins_Landing_Leg_Black_0.geometry}
                    material={materials.Landing_Leg_Black}
                  />
                </group>
              </group>
            </group>
            <group
              position={[0, 0, -2.999]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[1, 1, 5.823]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={
                  nodes.Cold_Gas_Thrusters_First_Stage_F9_Black_0.geometry
                }
                material={materials.F9_Black}
                rotation={[0, 0, Math.PI]}
              />
            </group>
            <group
              position={[0, 0, 0.624]}
              rotation={[0, 0, -2.618]}
              scale={[1, 1, 5.823]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={
                  nodes.Interstage_Engine_holder_F9_Second_Stage_0.geometry
                }
                material={materials.F9_Second_Stage}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={
                  nodes.Interstage_Engine_holder_extra_F9_Black_0.geometry
                }
                material={materials.F9_Black}
                rotation={[0, 0, -2.094]}
              />
            </group>
          </group>
          <group
            position={[-1.111, 1.333, 6.219]}
            rotation={[-2.413, -0.501, -0.508]}
            scale={[1, 0.986, 0.99]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes.Landing_Leg_Hydraulic_Holder_3_Landing_Leg_Black_0
                  .geometry
              }
              material={materials.Landing_Leg_Black}
            />
            <group position={[0, -0.032, 0.437]} rotation={[2.295, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={
                  nodes.Landing_Leg_Hydraulic_1003_Landing_Leg_Gray_0.geometry
                }
                material={materials.Landing_Leg_Gray}
              />
              <group position={[0, 0.003, 0.57]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes.Landing_Leg_Hydraulic_2003_Landing_Leg_Gray_0.geometry
                  }
                  material={materials.Landing_Leg_Gray}
                />
                <group position={[0, 0, 0.38]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.Landing_Leg_Hydraulic_3003_Landing_Leg_Gray_0
                        .geometry
                    }
                    material={materials.Landing_Leg_Gray}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.Landing_Leg_Hydraulic_4003_Landing_Leg_Gray_0
                        .geometry
                    }
                    material={materials.Landing_Leg_Gray}
                    position={[0, 0, 1.38]}
                  />
                </group>
              </group>
            </group>
          </group>
          <group
            position={[1.333, 1.111, 6.219]}
            rotation={[-2.5, 0.615, 0.676]}
            scale={[1, 0.986, 0.99]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes.Landing_Leg_Hydraulic_Holder_2_Landing_Leg_Black_0
                  .geometry
              }
              material={materials.Landing_Leg_Black}
            />
            <group position={[0, -0.032, 0.437]} rotation={[2.295, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={
                  nodes.Landing_Leg_Hydraulic_1002_Landing_Leg_Gray_0.geometry
                }
                material={materials.Landing_Leg_Gray}
              />
              <group position={[0, 0.003, 0.57]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes.Landing_Leg_Hydraulic_2002_Landing_Leg_Gray_0.geometry
                  }
                  material={materials.Landing_Leg_Gray}
                />
                <group position={[0, 0, 0.38]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.Landing_Leg_Hydraulic_3002_Landing_Leg_Gray_0
                        .geometry
                    }
                    material={materials.Landing_Leg_Gray}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.Landing_Leg_Hydraulic_4002_Landing_Leg_Gray_0
                        .geometry
                    }
                    material={materials.Landing_Leg_Gray}
                    position={[0, 0, 1.38]}
                  />
                </group>
              </group>
            </group>
          </group>
          <group
            position={[1.111, -1.333, 6.219]}
            rotation={[2.433, 0.536, 2.708]}
            scale={[1, 0.986, 0.99]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes.Landing_Leg_Hydraulic_Holder_1_Landing_Leg_Black_0
                  .geometry
              }
              material={materials.Landing_Leg_Black}
            />
            <group position={[0, -0.032, 0.437]} rotation={[2.295, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={
                  nodes.Landing_Leg_Hydraulic_1001_Landing_Leg_Gray_0.geometry
                }
                material={materials.Landing_Leg_Gray}
              />
              <group position={[0, 0.003, 0.57]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes.Landing_Leg_Hydraulic_2001_Landing_Leg_Gray_0.geometry
                  }
                  material={materials.Landing_Leg_Gray}
                />
                <group position={[0, 0, 0.38]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.Landing_Leg_Hydraulic_3001_Landing_Leg_Gray_0
                        .geometry
                    }
                    material={materials.Landing_Leg_Gray}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.Landing_Leg_Hydraulic_4001_Landing_Leg_Gray_0
                        .geometry
                    }
                    material={materials.Landing_Leg_Gray}
                    position={[0, 0, 1.38]}
                  />
                </group>
              </group>
            </group>
          </group>
          <group
            position={[-1.333, -1.111, 6.219]}
            rotation={[2.524, -0.641, -2.522]}
            scale={[1, 0.986, 0.99]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes.Landing_Leg_Hydraulic_Holder_4_Landing_Leg_Black_0
                  .geometry
              }
              material={materials.Landing_Leg_Black}
            />
            <group position={[0, -0.032, 0.437]} rotation={[2.295, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={
                  nodes.Landing_Leg_Hydraulic_1004_Landing_Leg_Gray_0.geometry
                }
                material={materials.Landing_Leg_Gray}
              />
              <group position={[0, 0.003, 0.57]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes.Landing_Leg_Hydraulic_2004_Landing_Leg_Gray_0.geometry
                  }
                  material={materials.Landing_Leg_Gray}
                />
                <group position={[0, 0, 0.38]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.Landing_Leg_Hydraulic_3004_Landing_Leg_Gray_0
                        .geometry
                    }
                    material={materials.Landing_Leg_Gray}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.Landing_Leg_Hydraulic_4004_Landing_Leg_Gray_0
                        .geometry
                    }
                    material={materials.Landing_Leg_Gray}
                    position={[0, 0, 1.38]}
                  />
                </group>
              </group>
            </group>
          </group>
          <group rotation={[0, 0, 1.48]} scale={[1, 1, 0.975]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Octaweb_F9_Octaweb_Black_0.geometry}
              material={materials.F9_Octaweb_Black}
              rotation={[0, 0, -Math.PI / 4]}
            />
          </group>
          <group rotation={[0, 0, 1.178]} scale={[1, 1, 0.975]}>
            <group rotation={[0, 0, -Math.PI / 4]}>
              <mesh
                castShadow
                receiveShadow
                geometry={
                  nodes.Merlin_1D_Engine_Outer_Merlin_Engine_2_0.geometry
                }
                material={materials.Merlin_Engine_2}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={
                  nodes.Merlin_1D_Engine_Outer_Merlin_Engine_1_0.geometry
                }
                material={materials.Merlin_Engine_1}
              />
            </group>
            <group position={[-0.518, 1.251, -0.098]} rotation={[0, 0, -1.178]}>
              <mesh
                castShadow
                receiveShadow
                geometry={
                  nodes.Merlin_1D_Engine_Center_Merlin_Engine_2_0.geometry
                }
                material={materials.Merlin_Engine_2}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={
                  nodes.Merlin_1D_Engine_Center_Merlin_Engine_1_0.geometry
                }
                material={materials.Merlin_Engine_1}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Engine_Cloth_Engine_Cloth_Black_0.geometry}
              material={materials.Engine_Cloth_Black}
              rotation={[0, 0, -Math.PI / 4]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Engine_Holder_Detail_Outer_F9_Black_0.geometry}
              material={materials.F9_Black}
              rotation={[0, 0, -Math.PI / 4]}
            />
          </group>
          <group
            position={[-1.979, 0.173, 16.749]}
            rotation={[0, 0, -0.087]}
            scale={[1, 1, 0.975]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Raceway_Main_First_Stage_F9_Black_0.geometry}
              material={materials.F9_Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes.Raceway_Main_Detail_2_First_Stage_F9_Black_0.geometry
              }
              material={materials.F9_Black}
              position={[0, 0, 23.808]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes.Raceway_Main_Detail_First_Stage_F9_Black_0.geometry
              }
              material={materials.F9_Black}
            />
          </group>
          <group
            position={[1.979, -0.173, 16.749]}
            rotation={[0, 0, 3.054]}
            scale={[1, 1, 0.975]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Raceway_First_Stage_F9_Black_0.geometry}
              material={materials.F9_Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Raceway_Holders_2_First_Stage_F9_Black_0.geometry}
              material={materials.F9_Black}
              position={[0, 0, -6.877]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Raceway_Holders_1_First_Stage_F9_Black_0.geometry}
              material={materials.F9_Black}
            />
          </group>
          <group
            position={[0, 0, 1.828]}
            rotation={[0, 0, 1.48]}
            scale={[1, 1, 0.975]}
          >
            <group rotation={[0, 0, -Math.PI / 2]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Landing_Leg_Holders_F9_Black_0.geometry}
                material={materials.F9_Black}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Landing_Leg_Holders_Metal_White_Gold_0.geometry}
                material={materials.Metal_White_Gold}
              />
            </group>
          </group>
          <group
            position={[0, 0, 1.828]}
            rotation={[0, 0, -2.074]}
            scale={[1, 1, 0.975]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes.First_Stage_Bottom_Things_Landing_Leg_Black_0.geometry
              }
              material={materials.Landing_Leg_Black}
              rotation={[0, 0, Math.PI]}
            />
          </group>
          <group
            position={[0, 0, 1.828]}
            rotation={[0, 0, 2.266]}
            scale={[1, 1, 0.975]}
          >
            <group position={[0, -1.511, 0.109]} rotation={[0, 0, Math.PI / 2]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Landing_Leg_2_Landing_Leg_Black_0.geometry}
                material={materials.Landing_Leg_Black}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Landing_Leg_2_Landing_Leg_White_0.geometry}
                material={materials.Landing_Leg_White}
              />
              <group position={[-0.384, 0.001, 8.73]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes.Landing_Leg_2_Hydraulic_Attachment_Metal_White_Gold_0
                      .geometry
                  }
                  material={materials.Metal_White_Gold}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes.Landing_Leg_2_Hydraulic_Attachment_Landing_Leg_Black_0
                      .geometry
                  }
                  material={materials.Landing_Leg_Black}
                />
              </group>
            </group>
            <group position={[-1.511, 0, 0.109]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Landing_Leg_1_Landing_Leg_Black_0.geometry}
                material={materials.Landing_Leg_Black}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Landing_Leg_1_Landing_Leg_White_0.geometry}
                material={materials.Landing_Leg_White}
              />
              <group position={[-0.384, 0.001, 8.73]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes.Landing_Leg_1_Hydraulic_Attachment_Metal_White_Gold_0
                      .geometry
                  }
                  material={materials.Metal_White_Gold}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes.Landing_Leg_1_Hydraulic_Attachment_Landing_Leg_Black_0
                      .geometry
                  }
                  material={materials.Landing_Leg_Black}
                />
              </group>
            </group>
            <group position={[0, 1.511, 0.109]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Landing_Leg_4_Landing_Leg_Black_0.geometry}
                material={materials.Landing_Leg_Black}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Landing_Leg_4_Landing_Leg_White_0.geometry}
                material={materials.Landing_Leg_White}
              />
              <group position={[-0.384, 0.001, 8.73]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes.Landing_Leg_4_Hydraulic_Attachment_Metal_White_Gold_0
                      .geometry
                  }
                  material={materials.Metal_White_Gold}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes.Landing_Leg_4_Hydraulic_Attachment_Landing_Leg_Black_0
                      .geometry
                  }
                  material={materials.Landing_Leg_Black}
                />
              </group>
            </group>
            <group position={[1.511, 0, 0.109]} rotation={[0, 0, Math.PI]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Landing_Leg_3_Landing_Leg_Black_0.geometry}
                material={materials.Landing_Leg_Black}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Landing_Leg_3_Landing_Leg_White_0.geometry}
                material={materials.Landing_Leg_White}
              />
              <group position={[-0.384, 0.001, 8.73]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes.Landing_Leg_3_Hydraulic_Attachment_Metal_White_Gold_0
                      .geometry
                  }
                  material={materials.Metal_White_Gold}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes.Landing_Leg_3_Hydraulic_Attachment_Landing_Leg_Black_0
                      .geometry
                  }
                  material={materials.Landing_Leg_Black}
                />
              </group>
            </group>
          </group>
          <group position={[0, 0, 46.11]} scale={[1, 1, 0.975]}>
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes.Second_Stage_Detacher_Interstage_F9_Black_0.geometry
              }
              material={materials.F9_Black}
              rotation={[0, 0, -2.094]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Landing_Leg_Clamps_Landing_Leg_Black_0.geometry}
            material={materials.Landing_Leg_Black}
            position={[0, 0, 1.828]}
            rotation={[0, 0, 0.695]}
            scale={[1, 1, 0.975]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Grid_Fin_Holders_F9_First_Stage_0.geometry}
            material={materials.F9_First_Stage}
            position={[0, 0, 40.141]}
            rotation={[0, 0, 0.786]}
            scale={[1, 1, 0.975]}
          />
        </group>
        <group position={[0, 57.977, 0]} rotation={[0, Math.PI / 2, 0]}>
          <group rotation={[-Math.PI / 2, 0, -Math.PI]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Fairing_2_F9_Fairing_0.geometry}
              material={materials.F9_Fairing}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Fairing_2_Detail_F9_Fairing_0.geometry}
              material={materials.F9_Fairing}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, -Math.PI]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Fairing_1_F9_Fairing_0.geometry}
              material={materials.F9_Fairing}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Fairing_1_Detail_F9_Fairing_0.geometry}
              material={materials.F9_Fairing}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/falcon.glb");
