/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Anthony Yanez (https://sketchfab.com/paulyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/neptune-7e7632f6e16b4aaaa7597b9ff91b47b2
Title: Neptune
*/
"use client";
import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Neptune(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/neptune.glb");
  const { actions } = useAnimations(animations, group);
  useFrame(() => {
    group.current.rotation.y += 0.007;
  });
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={[0.005, 0.005, 0.005]}
      rotation={[0.4, -1, 0]}
      position={[0, 0.75, 0]}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="NeptuneFBX" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Neptune" rotation={[-1.833, 0, 0]} scale={3.9}>
                  <mesh
                    name="Neptune_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Neptune_01_-_Default_0"].geometry}
                    material={materials["01_-_Default"]}
                  />
                </group>
                <group
                  name="Triton"
                  rotation={[-1.617, -0.258, 1.39]}
                  scale={0.25}
                >
                  <mesh
                    name="Triton_02_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Triton_02_-_Default_0"].geometry}
                    material={materials["02_-_Default"]}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/neptune.glb");
